// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1w1HRmPUO_Q0ilesHl_YBTa0zWsCQjXM',
    appId: '1:328638093804:web:acb96f1f62fb6393bec8c9',
    messagingSenderId: '328638093804',
    projectId: 'cozynotes-e924b',
    authDomain: 'cozynotes-e924b.firebaseapp.com',
    storageBucket: 'cozynotes-e924b.firebasestorage.app',
    measurementId: 'G-D3CF3XECDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyq3NaEeKFORBXsxZR6v-egQGyZ32RyQ4',
    appId: '1:328638093804:android:44104b4df1534310bec8c9',
    messagingSenderId: '328638093804',
    projectId: 'cozynotes-e924b',
    storageBucket: 'cozynotes-e924b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB6aFtgyHLpszbLQhuSDCIFyYXhqOGNdE',
    appId: '1:328638093804:ios:590f5a5b281a803cbec8c9',
    messagingSenderId: '328638093804',
    projectId: 'cozynotes-e924b',
    storageBucket: 'cozynotes-e924b.firebasestorage.app',
    iosBundleId: 'com.example.cozyNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB6aFtgyHLpszbLQhuSDCIFyYXhqOGNdE',
    appId: '1:328638093804:ios:590f5a5b281a803cbec8c9',
    messagingSenderId: '328638093804',
    projectId: 'cozynotes-e924b',
    storageBucket: 'cozynotes-e924b.firebasestorage.app',
    iosBundleId: 'com.example.cozyNote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1w1HRmPUO_Q0ilesHl_YBTa0zWsCQjXM',
    appId: '1:328638093804:web:9cc3598071f877c0bec8c9',
    messagingSenderId: '328638093804',
    projectId: 'cozynotes-e924b',
    authDomain: 'cozynotes-e924b.firebaseapp.com',
    storageBucket: 'cozynotes-e924b.firebasestorage.app',
    measurementId: 'G-F8LJL5SCXB',
  );
}
